export const products = [
  {
    id: 1,
    name: "Nike React Infinity Run",
    brand: "NIKE",
    gender: "MEN",
    category: "RUNNING",
    price: 160,
    is_in_inventory: true,
    items_left: 3,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0bf33c0a-4551-4ea3-a2c7-dec261cbdf56/air-zoom-pegasus-37-running-shoe-qVSCSr.jpg",
    slug: "nike-react-infinity-run-flyknit",
  },
  {
    id: 2,
    name: "Nike React Miler",
    brand: "NIKE",
    gender: "MEN",
    category: "RUNNING",
    price: 130,
    is_in_inventory: true,
    items_left: 3,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/03119662-2585-4658-bed3-1fa9a19196c2/air-zoom-pegasus-37-running-shoe-Z7QV8F.jpg",
    slug: "nike-react-miler",
  },
  {
    id: 3,
    name: "Nike Mercurial Vapor 13",
    brand: "NIKE",
    gender: "MEN",
    category: "FOOTBALL",
    price: 145,
    is_in_inventory: true,
    items_left: 3,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/98403112-6391-4f29-80b8-0eb82264d98c/air-zoom-pegasus-37-running-shoe-Z7QV8F.jpg",
    slug: "nike-mercurial-vapor-13-elite-tech-craft-fg",
  },
  {
    id: 4,
    name: "Nike Mercurial Superfly",
    brand: "NIKE",
    gender: "MEN",
    category: "FOOTBALL",
    price: 137,
    is_in_inventory: true,
    items_left: 3,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7bf18c90-ea09-4963-9ae4-cb4ae8f6fc1f/air-zoom-pegasus-37-running-shoe-Z7QV8F.jpg",
    slug: "nike-mercurial-superfly-7-pro-mds-fg",
  },
  {
    id: 5,
    name: "Bridgport Advice",
    brand: "HUSHPUPPIES",
    gender: "MEN",
    category: "FORMAL",
    price: 30,
    is_in_inventory: true,
    items_left: 4,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/049ee600-6862-459b-ba89-883a5c59b0f2/air-zoom-pegasus-37-running-shoe-Z7QV8F.jpg",
    slug: "bridgport-advice",
  },
  {
    id: 6,
    name: "Beck",
    brand: "HUSHPUPPIES",
    gender: "MEN",
    category: "FORMAL",
    price: 80,
    is_in_inventory: true,
    items_left: 5,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1e13dabf-e6c6-4430-aa51-1443d9eda9f9/air-zoom-pegasus-37-running-shoe-Z7QV8F.jpg",
    slug: "beck",
  },
  {
    id: 7,
    name: "Fester",
    brand: "HUSHPUPPIES",
    gender: "MEN",
    category: "FORMAL",
    price: 70,
    is_in_inventory: true,
    items_left: 6,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/edb94cfd-9472-45de-a932-80a73613f847/nikecourt-air-zoom-gp-turbo-hard-court-tennis-shoe-C8Z2Hj.jpg",
    slug: "fester",
  },
  {
    id: 8,
    name: "Pixel",
    brand: "HUSHPUPPIES",
    gender: "MEN",
    category: "FORMAL",
    price: 75,
    is_in_inventory: true,
    items_left: 7,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/74623394-5112-44fa-91f2-bc5c8820a138/air-zoom-superrep-hiit-class-shoe-x6Kv5r.jpg",
    slug: "pixel",
  },
  {
    id: 9,
    name: "Austin",
    brand: "HUSHPUPPIES",
    gender: "MEN",
    category: "FORMAL",
    price: 75,
    is_in_inventory: true,
    items_left: 2,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9550d971-9d16-4cb3-b593-4484a74dda11/air-max-verona-shoe-PHJTlW.jpg",
    slug: "austin",
  },
  {
    id: 10,
    name: "Club C Revenge Mens",
    brand: "Reebok",
    gender: "MEN",
    category: "CASUAL",
    price: 70,
    is_in_inventory: true,
    items_left: 3,
    imageURL:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/fb115fcc-b2f5-4bb7-9723-5d1b8e93a475/blazer-mid-vintage-77-shoe-xr8s4P.jpg",
    slug: "club-c-revenge-mens",
  },
  {
    id: 11,
    name: "SK80-Low",
    brand: "Vans",
    gender: "MEN",
    category: "CASUAL",
    price: 60,
    is_in_inventory: true,
    items_left: 3,
    imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/452ba8fd-6244-4d1e-b946-eb4da108c8bf/react-vision-shoe-lPbm3g.jpg",
    slug: "sk80-low",
  },
  {
    id: 12,
    name: "Michael Feburary SK8-Hi",
    brand: "Vans",
    gender: "MEN",
    category: "CASUAL",
    price: 72,
    is_in_inventory: true,
    items_left: 3,
    imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/3c530538-6cea-40d4-9e8c-b117776e68f2/nikecourt-air-zoom-vapor-hard-court-tennis-shoe-bkTvGWJw.jpg",
    slug: "michael-feburary-sk8-hi",
  },
];